### PR TITLE
WIP: Feature/replay tool settings

### PR DESCRIPTION
**Pull request by bewakes**

### CODE REVIEW

**Comment by danbjoseph** [comment]
following @mojodna's instructions at https://github.com/posm/posm-build/blob/master/live/README.md
i ran into this:
```
Disk usage after telegraf:
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p1   97G   92G  5.1G  95% /
none            492K     0  492K   0% /dev
udev             16G     0   16G   0% /dev/fuse
tmpfs           100K     0  100K   0% /dev/lxd
tmpfs           100K     0  100K   0% /dev/.lxd-mounts
tmpfs            16G  8.0K   16G   1% /dev/shm
tmpfs            16G  1.9M   16G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
overlay          97G   92G  5.1G  95% /var/lib/docker/overlay2/47bc6038ce8ed24835b0ba3bf09b2bc7b324b415e7b8ed222eccb438c80582e9/merged
[Fri Jan 10 17:20:40 2020] Bootstrap complete: 0
lxc snapshot $(cat container) telegraf
Error: failed to rsync: rsync: write failed on "/var/lib/lxd/storage-pools/default/snapshots/valid-roughy/telegraf/rootfs/usr/lib/x86_64-linux-gnu/libicudata.a": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]
: Failed to run: rsync -a -HAX --sparse --devices --delete --checksum --numeric-ids --xattrs --bwlimit 0 -q /var/lib/lxd/storage-pools/default/containers/valid-roughy/ /var/lib/lxd/storage-pools/default/snapshots/valid-roughy/telegraf: rsync: write failed on "/var/lib/lxd/storage-pools/default/snapshots/valid-roughy/telegraf/rootfs/usr/lib/x86_64-linux-gnu/libicudata.a": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]
Makefile:148: recipe for target 'telegraf' failed
make: *** [telegraf] Error 1
```
retrying with more disk storage.

**Comment by bewakes** [comment]
That's weird, this PR has nothing to do with telegraf. Maybe less disk space is the problem

**Comment by danbjoseph** [comment]
balenaEtcher doesn't like the ISO file. trying again.
Screen Shot 2020-01-14 at 10 42 34 AM

**Comment by danbjoseph** [comment]
needed to reinstall balenaEtcher. upgrading to macOS Catalina broke the previous install.

**Comment by danbjoseph** [comment]
First install attempt showed this:
IMG_20200115_095458
Then pressing **Enter** for reboot trigger led to this:
IMG_20200115_105731
Second install attempt led to a successful reboot.
Where should the posm-replay tool be accessible from? Should I see a side-nav item?
Screen Shot 2020-01-15 at 11 30 02 AM

**Comment by bewakes** [comment]
Oops, we forgot to include that in the UI. We'll just fix that and let you know. In the mean time, please try: `replay-tool.posm.io`. But first, you have to modify the .env file whose path is `/opt/replay-tool/posm-replay-server/.env`. The file should have comments about what the values should be. Once done, you need to restart the service `replay-tool`. Please try this and let us know.

**Comment by bewakes** [comment]
Here's deploy notes
https://github.com/posm/posm-replay-server/blob/master/Deploy-Notes.md

**Comment by danbjoseph** [comment]
ran an [ISO creation](https://github.com/toggle-corp/posm-build/tree/feature/replay-tool-settings/live#iso-creation) using your fork
```
GIT_REPO=https://github.com/toggle-corp/posm-build GIT_BRANCH=feature/replay-tool-settings make
```
and i don't see the `/opt/replay-tool/` folder after install on a POSM
Screen Shot 2020-02-04 at 10 22 37 AM
and going to https://replay-tool.posm.io/ gives me an `ERR_CONNECTION_CLOSED`

**Comment by bewakes** [comment]
We'll try to build the iso ourselves and let you know.

**Comment by bewakes** [comment]
We tried to build the iso in the NUC itself, but it keeps failing. Is it because of different version of ubuntu in NUC?
And the directory `/opt/replay-tool/` should have clearly been created from this script: https://github.com/toggle-corp/posm-build/blob/feature%2Freplay-tool-settings/kickstart/scripts/replay-tool-deploy.sh#L9

I've fixed some probable issues in the script and forced pushed them. So maybe could you try it again?
Also, could it be that because the script name is `replay-tool-deploy.sh` while all the other scripts have name <single_word>-deploy.sh ? Maybe the names should be in certain format.

**Comment by danbjoseph** [comment]
i'm on work travel this week and unable to test the install on a physical device but i built the ISO from your branch:
https://arcmaps.s3.amazonaws.com/share/tmp/posm-20200210.iso
and the logged output from the build:
https://arcmaps.s3.amazonaws.com/share/tmp/posm-20200210.txt

**Comment by bewakes** [comment]
Great, thanks!!

**Comment by danbjoseph** [comment]
i installed using the ISO and i still don't see the `/opt/posm-replay folder`
i ran the ISO build using:
```
GIT_REPO=https://github.com/toggle-corp/posm-build GIT_BRANCH=feature/replay-tool-settings make &>> /home/ubuntu/posm-20200210.txt
```

**Comment by bewakes** [comment]
Thanks for the log output. I looked into it and found out that somehow make for target `replay-tool` is not run, although it is included in the Makefile(https://github.com/toggle-corp/posm-build/blob/feature/replay-tool-settings/live/Makefile#L152-L158)
Then I tried to build it myself in NUC but I got this weird error.
```
root@posm:~/posm-build/live# make
lxc exec $(cat container) -- apt install -y --no-install-recommends git
Error: not found
Makefile:26: recipe for target 'base' failed
make: *** [base] Error 1
```

**Comment by bewakes** [comment]
We are again trying from scratch in a fresh ec2 ubuntu(18.04) instance. Will let you know.

**Comment by bewakes** [comment]
Hi @danbjoseph , from the log you shared in the previous comment, I could see no target for `replay-tool` being built. Did you try running the `GIT_REPO=https://github.com/toggle-corp/posm-build GIT_BRANCH=feature/replay-tool-settings make &>> /home/ubuntu/posm-20200210.txt` command from `feature/replay-tool-settings` branch itself?

Apparently, it seems that only setting the environment variables for git repo and branch is not sufficient.

**Comment by danbjoseph** [comment]
still seeing this message at the end of the install..
IMG_20200304_134204

but the `/opt/replay-tool` folder was created
IMG_20200304_134501

will explore more

**Comment by bewakes** [comment]
This PR has been integrated with posm auth settings into a new one:
https://github.com/posm/posm-build/pull/128

**Pull request closed without merging**
