### PR TITLE
Ensure that dnsmasq runs on wlan0

### PR DESCRIPTION
**Pull request by JeremyGrosser**

### CODE REVIEW

**Comment by sethfitz** [comment]
`posm_netif` _is_ (usually) `wlan0`, so doesn't this do the opposite?

**Comment by JeremyGrosser** [comment]
Right. {{posm_wan_netif}} is p2p0, {{posm_netif}} is wlan0. Before this change, {{posm_netif}} was not being added to the dnsmasq args, causing dnsmasq to only run on p2p0.

**Comment by sethfitz** [comment]
I'm getting confused by the `EXCEPT` bit.

**Comment by JeremyGrosser** [comment]
You're totally right, I missed that part. Please ignore me :)

**Pull request closed without merging**
