### PR TITLE
iso creation instruction updates [WIP]

### PR DESCRIPTION
**Pull request by danbjoseph**

### CODE REVIEW

**Comment by danbjoseph** [comment]
If my changes are on a branch of the main repo, and I checkout my branch with the features before running the `make` commands, do I need to do the following from the readme?

---------

The git repo and branch used to bootstrap the installer can be provided as
environment variables, allowing for builds containing experimental features:
```bash
GIT_REPO=https://github.com/mojodna/posm-build GIT_BRANCH=integration make
```

**Comment by sethfitz** [comment]
Yes, all branches default to building the container with `master`. The other caveat is that branches need to have been pushed in order to get pulled correctly from within the container.

**Comment by danbjoseph** [comment]
see posm/posm#353 for problem encountered in this process

**Comment by danbjoseph** [comment]
related https://github.com/posm/docs/issues/19

**Pull request closed without merging**
